spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/statistics
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: statisticsdemo
    
mybatis:
  mapper-locations: classpath:mapper/*.xml